// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protos/guard/guard.proto

package guard

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	shared "github.com/tron-us/go-btfs-common/protos/shared"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCode int32

const (
	ResponseCode_SUCCESS                ResponseCode = 0
	ResponseCode_SIGNATURE_FORMAT_ERROR ResponseCode = 1
	ResponseCode_COMPUTE_ADDRESS_ERROR  ResponseCode = 2
	ResponseCode_OTHER_ERROR            ResponseCode = 20
)

var ResponseCode_name = map[int32]string{
	0:  "SUCCESS",
	1:  "SIGNATURE_FORMAT_ERROR",
	2:  "COMPUTE_ADDRESS_ERROR",
	20: "OTHER_ERROR",
}

var ResponseCode_value = map[string]int32{
	"SUCCESS":                0,
	"SIGNATURE_FORMAT_ERROR": 1,
	"COMPUTE_ADDRESS_ERROR":  2,
	"OTHER_ERROR":            20,
}

func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}

func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{0}
}

type ContractMeta_Schedule int32

const (
	ContractMeta_MONTHLY   ContractMeta_Schedule = 0
	ContractMeta_QUARTERLY ContractMeta_Schedule = 1
	ContractMeta_ANNUALLY  ContractMeta_Schedule = 2
)

var ContractMeta_Schedule_name = map[int32]string{
	0: "MONTHLY",
	1: "QUARTERLY",
	2: "ANNUALLY",
}

var ContractMeta_Schedule_value = map[string]int32{
	"MONTHLY":   0,
	"QUARTERLY": 1,
	"ANNUALLY":  2,
}

func (x ContractMeta_Schedule) String() string {
	return proto.EnumName(ContractMeta_Schedule_name, int32(x))
}

func (ContractMeta_Schedule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{1, 0}
}

type Contract_ContractState int32

const (
	Contract_DRAFT    Contract_ContractState = 0
	Contract_SIGNED   Contract_ContractState = 1
	Contract_UPLOADED Contract_ContractState = 2
	Contract_LOST     Contract_ContractState = 3
	Contract_CANCELED Contract_ContractState = 4
	Contract_CLOSED   Contract_ContractState = 5
)

var Contract_ContractState_name = map[int32]string{
	0: "DRAFT",
	1: "SIGNED",
	2: "UPLOADED",
	3: "LOST",
	4: "CANCELED",
	5: "CLOSED",
}

var Contract_ContractState_value = map[string]int32{
	"DRAFT":    0,
	"SIGNED":   1,
	"UPLOADED": 2,
	"LOST":     3,
	"CANCELED": 4,
	"CLOSED":   5,
}

func (x Contract_ContractState) String() string {
	return proto.EnumName(Contract_ContractState_name, int32(x))
}

func (Contract_ContractState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{2, 0}
}

type FileStoreStatus_MetaState int32

const (
	FileStoreStatus_DRAFT        FileStoreStatus_MetaState = 0
	FileStoreStatus_UPLOADING    FileStoreStatus_MetaState = 1
	FileStoreStatus_RUNNING      FileStoreStatus_MetaState = 2
	FileStoreStatus_PARTIAL_LOST FileStoreStatus_MetaState = 3
	FileStoreStatus_LOST         FileStoreStatus_MetaState = 4
	FileStoreStatus_DONE         FileStoreStatus_MetaState = 5
)

var FileStoreStatus_MetaState_name = map[int32]string{
	0: "DRAFT",
	1: "UPLOADING",
	2: "RUNNING",
	3: "PARTIAL_LOST",
	4: "LOST",
	5: "DONE",
}

var FileStoreStatus_MetaState_value = map[string]int32{
	"DRAFT":        0,
	"UPLOADING":    1,
	"RUNNING":      2,
	"PARTIAL_LOST": 3,
	"LOST":         4,
	"DONE":         5,
}

func (x FileStoreStatus_MetaState) String() string {
	return proto.EnumName(FileStoreStatus_MetaState_name, int32(x))
}

func (FileStoreStatus_MetaState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{4, 0}
}

type Log struct {
	ChangeTime           *types.Timestamp `protobuf:"bytes,1,opt,name=change_time,json=changeTime,proto3" json:"change_time,omitempty"`
	ChangeOriginator     []byte           `protobuf:"bytes,2,opt,name=change_originator,json=changeOriginator,proto3" json:"change_originator,omitempty"`
	Change               []byte           `protobuf:"bytes,3,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{0}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetChangeTime() *types.Timestamp {
	if m != nil {
		return m.ChangeTime
	}
	return nil
}

func (m *Log) GetChangeOriginator() []byte {
	if m != nil {
		return m.ChangeOriginator
	}
	return nil
}

func (m *Log) GetChange() []byte {
	if m != nil {
		return m.Change
	}
	return nil
}

//the relationship of the objects from Guard's view
// FileStoreMeta (1:n) Contract (1:n) payout
//contract is the signed document between the renter and host for one shard's storage
// the contract information contains buyer, seller, escrow, guard , storage shard's information, rent duration, amount, payment method(periodically and times)
//ContractMeta is the information which will not be changed after proposal
//Contract technically is the contract execution record, it contains the contractMeta and state information
type ContractMeta struct {
	//Contract proposed by renter, will not be changed after renter proposed
	ContractId           []byte                `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	RenterAddress        []byte                `protobuf:"bytes,2,opt,name=renter_address,json=renterAddress,proto3" json:"renter_address,omitempty"`
	HostAddress          []byte                `protobuf:"bytes,3,opt,name=host_address,json=hostAddress,proto3" json:"host_address,omitempty"`
	ShardHash            []byte                `protobuf:"bytes,4,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`
	ShardIndex           int32                 `protobuf:"varint,5,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	ShardFileSize        int64                 `protobuf:"varint,6,opt,name=shard_file_size,json=shardFileSize,proto3" json:"shard_file_size,omitempty"`
	FileHash             []byte                `protobuf:"bytes,7,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	RentStart            *time.Time            `protobuf:"bytes,8,opt,name=rent_start,json=rentStart,proto3,stdtime" json:"rent_start,omitempty"`
	RentEnd              *time.Time            `protobuf:"bytes,9,opt,name=rent_end,json=rentEnd,proto3,stdtime" json:"rent_end,omitempty"`
	GuardAddress         []byte                `protobuf:"bytes,10,opt,name=guard_address,json=guardAddress,proto3" json:"guard_address,omitempty"`
	EscrowAddress        []byte                `protobuf:"bytes,11,opt,name=escrow_address,json=escrowAddress,proto3" json:"escrow_address,omitempty"`
	Price                int64                 `protobuf:"varint,12,opt,name=price,proto3" json:"price,omitempty"`
	Amount               int64                 `protobuf:"varint,13,opt,name=amount,proto3" json:"amount,omitempty"`
	CollateralAmount     int64                 `protobuf:"varint,14,opt,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount,omitempty"`
	PayoutSchedule       ContractMeta_Schedule `protobuf:"varint,15,opt,name=payout_schedule,json=payoutSchedule,proto3,enum=guard.ContractMeta_Schedule" json:"payout_schedule,omitempty"`
	NumPayouts           int32                 `protobuf:"varint,16,opt,name=num_payouts,json=numPayouts,proto3" json:"num_payouts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ContractMeta) Reset()         { *m = ContractMeta{} }
func (m *ContractMeta) String() string { return proto.CompactTextString(m) }
func (*ContractMeta) ProtoMessage()    {}
func (*ContractMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{1}
}
func (m *ContractMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractMeta.Unmarshal(m, b)
}
func (m *ContractMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractMeta.Marshal(b, m, deterministic)
}
func (m *ContractMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractMeta.Merge(m, src)
}
func (m *ContractMeta) XXX_Size() int {
	return xxx_messageInfo_ContractMeta.Size(m)
}
func (m *ContractMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ContractMeta proto.InternalMessageInfo

func (m *ContractMeta) GetContractId() []byte {
	if m != nil {
		return m.ContractId
	}
	return nil
}

func (m *ContractMeta) GetRenterAddress() []byte {
	if m != nil {
		return m.RenterAddress
	}
	return nil
}

func (m *ContractMeta) GetHostAddress() []byte {
	if m != nil {
		return m.HostAddress
	}
	return nil
}

func (m *ContractMeta) GetShardHash() []byte {
	if m != nil {
		return m.ShardHash
	}
	return nil
}

func (m *ContractMeta) GetShardIndex() int32 {
	if m != nil {
		return m.ShardIndex
	}
	return 0
}

func (m *ContractMeta) GetShardFileSize() int64 {
	if m != nil {
		return m.ShardFileSize
	}
	return 0
}

func (m *ContractMeta) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *ContractMeta) GetRentStart() *time.Time {
	if m != nil {
		return m.RentStart
	}
	return nil
}

func (m *ContractMeta) GetRentEnd() *time.Time {
	if m != nil {
		return m.RentEnd
	}
	return nil
}

func (m *ContractMeta) GetGuardAddress() []byte {
	if m != nil {
		return m.GuardAddress
	}
	return nil
}

func (m *ContractMeta) GetEscrowAddress() []byte {
	if m != nil {
		return m.EscrowAddress
	}
	return nil
}

func (m *ContractMeta) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ContractMeta) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ContractMeta) GetCollateralAmount() int64 {
	if m != nil {
		return m.CollateralAmount
	}
	return 0
}

func (m *ContractMeta) GetPayoutSchedule() ContractMeta_Schedule {
	if m != nil {
		return m.PayoutSchedule
	}
	return ContractMeta_MONTHLY
}

func (m *ContractMeta) GetNumPayouts() int32 {
	if m != nil {
		return m.NumPayouts
	}
	return 0
}

type Contract struct {
	//the contract executor record, changed frequently after proposal
	Contract             *ContractMeta          `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	State                Contract_ContractState `protobuf:"varint,2,opt,name=state,proto3,enum=guard.Contract_ContractState" json:"state,omitempty"`
	RenterSignature      []byte                 `protobuf:"bytes,3,opt,name=renter_signature,json=renterSignature,proto3" json:"renter_signature,omitempty"`
	HostSignature        []byte                 `protobuf:"bytes,4,opt,name=host_signature,json=hostSignature,proto3" json:"host_signature,omitempty"`
	EscrowSignedTime     *time.Time             `protobuf:"bytes,5,opt,name=escrow_signed_time,json=escrowSignedTime,proto3,stdtime" json:"escrow_signed_time,omitempty"`
	EscrowSignature      []byte                 `protobuf:"bytes,6,opt,name=escrow_signature,json=escrowSignature,proto3" json:"escrow_signature,omitempty"`
	ChangeLog            []*Log                 `protobuf:"bytes,7,rep,name=change_log,json=changeLog,proto3" json:"change_log,omitempty"`
	LastModifyTime       *time.Time             `protobuf:"bytes,8,opt,name=last_modify_time,json=lastModifyTime,proto3,stdtime" json:"last_modify_time,omitempty"`
	GuardSignature       []byte                 `protobuf:"bytes,9,opt,name=guard_signature,json=guardSignature,proto3" json:"guard_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{2}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetContract() *ContractMeta {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *Contract) GetState() Contract_ContractState {
	if m != nil {
		return m.State
	}
	return Contract_DRAFT
}

func (m *Contract) GetRenterSignature() []byte {
	if m != nil {
		return m.RenterSignature
	}
	return nil
}

func (m *Contract) GetHostSignature() []byte {
	if m != nil {
		return m.HostSignature
	}
	return nil
}

func (m *Contract) GetEscrowSignedTime() *time.Time {
	if m != nil {
		return m.EscrowSignedTime
	}
	return nil
}

func (m *Contract) GetEscrowSignature() []byte {
	if m != nil {
		return m.EscrowSignature
	}
	return nil
}

func (m *Contract) GetChangeLog() []*Log {
	if m != nil {
		return m.ChangeLog
	}
	return nil
}

func (m *Contract) GetLastModifyTime() *time.Time {
	if m != nil {
		return m.LastModifyTime
	}
	return nil
}

func (m *Contract) GetGuardSignature() []byte {
	if m != nil {
		return m.GuardSignature
	}
	return nil
}

type FileStoreMeta struct {
	//file store meta prepared by renter, will not changed after proposal
	RenterAddress        []byte     `protobuf:"bytes,1,opt,name=renter_address,json=renterAddress,proto3" json:"renter_address,omitempty"`
	FileHash             []byte     `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileSize             int64      `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	RentStart            *time.Time `protobuf:"bytes,4,opt,name=rent_start,json=rentStart,proto3,stdtime" json:"rent_start,omitempty"`
	RentEnd              *time.Time `protobuf:"bytes,5,opt,name=rent_end,json=rentEnd,proto3,stdtime" json:"rent_end,omitempty"`
	CheckFrequency       int32      `protobuf:"varint,6,opt,name=check_frequency,json=checkFrequency,proto3" json:"check_frequency,omitempty"`
	GuardFee             int64      `protobuf:"varint,7,opt,name=guard_fee,json=guardFee,proto3" json:"guard_fee,omitempty"`
	EscrowFee            int64      `protobuf:"varint,8,opt,name=escrow_fee,json=escrowFee,proto3" json:"escrow_fee,omitempty"`
	ShardCount           int32      `protobuf:"varint,9,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	MinimumShards        int32      `protobuf:"varint,10,opt,name=minimum_shards,json=minimumShards,proto3" json:"minimum_shards,omitempty"`
	RecoverThreshold     int32      `protobuf:"varint,11,opt,name=recover_threshold,json=recoverThreshold,proto3" json:"recover_threshold,omitempty"`
	EscrowAddress        []byte     `protobuf:"bytes,12,opt,name=escrow_address,json=escrowAddress,proto3" json:"escrow_address,omitempty"`
	GuardAddress         []byte     `protobuf:"bytes,13,opt,name=guard_address,json=guardAddress,proto3" json:"guard_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileStoreMeta) Reset()         { *m = FileStoreMeta{} }
func (m *FileStoreMeta) String() string { return proto.CompactTextString(m) }
func (*FileStoreMeta) ProtoMessage()    {}
func (*FileStoreMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{3}
}
func (m *FileStoreMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStoreMeta.Unmarshal(m, b)
}
func (m *FileStoreMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStoreMeta.Marshal(b, m, deterministic)
}
func (m *FileStoreMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStoreMeta.Merge(m, src)
}
func (m *FileStoreMeta) XXX_Size() int {
	return xxx_messageInfo_FileStoreMeta.Size(m)
}
func (m *FileStoreMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStoreMeta.DiscardUnknown(m)
}

var xxx_messageInfo_FileStoreMeta proto.InternalMessageInfo

func (m *FileStoreMeta) GetRenterAddress() []byte {
	if m != nil {
		return m.RenterAddress
	}
	return nil
}

func (m *FileStoreMeta) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *FileStoreMeta) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileStoreMeta) GetRentStart() *time.Time {
	if m != nil {
		return m.RentStart
	}
	return nil
}

func (m *FileStoreMeta) GetRentEnd() *time.Time {
	if m != nil {
		return m.RentEnd
	}
	return nil
}

func (m *FileStoreMeta) GetCheckFrequency() int32 {
	if m != nil {
		return m.CheckFrequency
	}
	return 0
}

func (m *FileStoreMeta) GetGuardFee() int64 {
	if m != nil {
		return m.GuardFee
	}
	return 0
}

func (m *FileStoreMeta) GetEscrowFee() int64 {
	if m != nil {
		return m.EscrowFee
	}
	return 0
}

func (m *FileStoreMeta) GetShardCount() int32 {
	if m != nil {
		return m.ShardCount
	}
	return 0
}

func (m *FileStoreMeta) GetMinimumShards() int32 {
	if m != nil {
		return m.MinimumShards
	}
	return 0
}

func (m *FileStoreMeta) GetRecoverThreshold() int32 {
	if m != nil {
		return m.RecoverThreshold
	}
	return 0
}

func (m *FileStoreMeta) GetEscrowAddress() []byte {
	if m != nil {
		return m.EscrowAddress
	}
	return nil
}

func (m *FileStoreMeta) GetGuardAddress() []byte {
	if m != nil {
		return m.GuardAddress
	}
	return nil
}

type FileStoreStatus struct {
	FileStoreMeta        *FileStoreMeta            `protobuf:"bytes,1,opt,name=file_store_meta,json=fileStoreMeta,proto3" json:"file_store_meta,omitempty"`
	State                FileStoreStatus_MetaState `protobuf:"varint,2,opt,name=state,proto3,enum=guard.FileStoreStatus_MetaState" json:"state,omitempty"`
	Contracts            []*Contract               `protobuf:"bytes,3,rep,name=contracts,proto3" json:"contracts,omitempty"`
	RenterSignature      []byte                    `protobuf:"bytes,4,opt,name=renter_signature,json=renterSignature,proto3" json:"renter_signature,omitempty"`
	GuardReceiveTime     *time.Time                `protobuf:"bytes,5,opt,name=guard_receive_time,json=guardReceiveTime,proto3,stdtime" json:"guard_receive_time,omitempty"`
	ChangeLog            []*Log                    `protobuf:"bytes,6,rep,name=change_log,json=changeLog,proto3" json:"change_log,omitempty"`
	CurentTime           *time.Time                `protobuf:"bytes,7,opt,name=curent_time,json=curentTime,proto3,stdtime" json:"curent_time,omitempty"`
	GuardSignature       []byte                    `protobuf:"bytes,8,opt,name=guard_signature,json=guardSignature,proto3" json:"guard_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FileStoreStatus) Reset()         { *m = FileStoreStatus{} }
func (m *FileStoreStatus) String() string { return proto.CompactTextString(m) }
func (*FileStoreStatus) ProtoMessage()    {}
func (*FileStoreStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{4}
}
func (m *FileStoreStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStoreStatus.Unmarshal(m, b)
}
func (m *FileStoreStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStoreStatus.Marshal(b, m, deterministic)
}
func (m *FileStoreStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStoreStatus.Merge(m, src)
}
func (m *FileStoreStatus) XXX_Size() int {
	return xxx_messageInfo_FileStoreStatus.Size(m)
}
func (m *FileStoreStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStoreStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FileStoreStatus proto.InternalMessageInfo

func (m *FileStoreStatus) GetFileStoreMeta() *FileStoreMeta {
	if m != nil {
		return m.FileStoreMeta
	}
	return nil
}

func (m *FileStoreStatus) GetState() FileStoreStatus_MetaState {
	if m != nil {
		return m.State
	}
	return FileStoreStatus_DRAFT
}

func (m *FileStoreStatus) GetContracts() []*Contract {
	if m != nil {
		return m.Contracts
	}
	return nil
}

func (m *FileStoreStatus) GetRenterSignature() []byte {
	if m != nil {
		return m.RenterSignature
	}
	return nil
}

func (m *FileStoreStatus) GetGuardReceiveTime() *time.Time {
	if m != nil {
		return m.GuardReceiveTime
	}
	return nil
}

func (m *FileStoreStatus) GetChangeLog() []*Log {
	if m != nil {
		return m.ChangeLog
	}
	return nil
}

func (m *FileStoreStatus) GetCurentTime() *time.Time {
	if m != nil {
		return m.CurentTime
	}
	return nil
}

func (m *FileStoreStatus) GetGuardSignature() []byte {
	if m != nil {
		return m.GuardSignature
	}
	return nil
}

type ChallengeQuestion struct {
	ShardHash            []byte   `protobuf:"bytes,1,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`
	HostAddress          []byte   `protobuf:"bytes,2,opt,name=host_address,json=hostAddress,proto3" json:"host_address,omitempty"`
	ChunkIndex           int32    `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	RandomNonce          int32    `protobuf:"varint,4,opt,name=random_nonce,json=randomNonce,proto3" json:"random_nonce,omitempty"`
	ExpectAnswer         []byte   `protobuf:"bytes,5,opt,name=expect_answer,json=expectAnswer,proto3" json:"expect_answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChallengeQuestion) Reset()         { *m = ChallengeQuestion{} }
func (m *ChallengeQuestion) String() string { return proto.CompactTextString(m) }
func (*ChallengeQuestion) ProtoMessage()    {}
func (*ChallengeQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{5}
}
func (m *ChallengeQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChallengeQuestion.Unmarshal(m, b)
}
func (m *ChallengeQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChallengeQuestion.Marshal(b, m, deterministic)
}
func (m *ChallengeQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChallengeQuestion.Merge(m, src)
}
func (m *ChallengeQuestion) XXX_Size() int {
	return xxx_messageInfo_ChallengeQuestion.Size(m)
}
func (m *ChallengeQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_ChallengeQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_ChallengeQuestion proto.InternalMessageInfo

func (m *ChallengeQuestion) GetShardHash() []byte {
	if m != nil {
		return m.ShardHash
	}
	return nil
}

func (m *ChallengeQuestion) GetHostAddress() []byte {
	if m != nil {
		return m.HostAddress
	}
	return nil
}

func (m *ChallengeQuestion) GetChunkIndex() int32 {
	if m != nil {
		return m.ChunkIndex
	}
	return 0
}

func (m *ChallengeQuestion) GetRandomNonce() int32 {
	if m != nil {
		return m.RandomNonce
	}
	return 0
}

func (m *ChallengeQuestion) GetExpectAnswer() []byte {
	if m != nil {
		return m.ExpectAnswer
	}
	return nil
}

type ProofOfReplicateChallenge struct {
	Question             *ChallengeQuestion `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	ChallengeTime        *time.Time         `protobuf:"bytes,2,opt,name=challenge_time,json=challengeTime,proto3,stdtime" json:"challenge_time,omitempty"`
	GuardAddress         []byte             `protobuf:"bytes,3,opt,name=guard_address,json=guardAddress,proto3" json:"guard_address,omitempty"`
	GuardSignature       []byte             `protobuf:"bytes,4,opt,name=guard_signature,json=guardSignature,proto3" json:"guard_signature,omitempty"`
	HostAnswer           []byte             `protobuf:"bytes,5,opt,name=host_answer,json=hostAnswer,proto3" json:"host_answer,omitempty"`
	HostSignTime         *time.Time         `protobuf:"bytes,6,opt,name=host_sign_time,json=hostSignTime,proto3,stdtime" json:"host_sign_time,omitempty"`
	HostSignature        []byte             `protobuf:"bytes,7,opt,name=host_signature,json=hostSignature,proto3" json:"host_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProofOfReplicateChallenge) Reset()         { *m = ProofOfReplicateChallenge{} }
func (m *ProofOfReplicateChallenge) String() string { return proto.CompactTextString(m) }
func (*ProofOfReplicateChallenge) ProtoMessage()    {}
func (*ProofOfReplicateChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{6}
}
func (m *ProofOfReplicateChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofOfReplicateChallenge.Unmarshal(m, b)
}
func (m *ProofOfReplicateChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofOfReplicateChallenge.Marshal(b, m, deterministic)
}
func (m *ProofOfReplicateChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofOfReplicateChallenge.Merge(m, src)
}
func (m *ProofOfReplicateChallenge) XXX_Size() int {
	return xxx_messageInfo_ProofOfReplicateChallenge.Size(m)
}
func (m *ProofOfReplicateChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofOfReplicateChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_ProofOfReplicateChallenge proto.InternalMessageInfo

func (m *ProofOfReplicateChallenge) GetQuestion() *ChallengeQuestion {
	if m != nil {
		return m.Question
	}
	return nil
}

func (m *ProofOfReplicateChallenge) GetChallengeTime() *time.Time {
	if m != nil {
		return m.ChallengeTime
	}
	return nil
}

func (m *ProofOfReplicateChallenge) GetGuardAddress() []byte {
	if m != nil {
		return m.GuardAddress
	}
	return nil
}

func (m *ProofOfReplicateChallenge) GetGuardSignature() []byte {
	if m != nil {
		return m.GuardSignature
	}
	return nil
}

func (m *ProofOfReplicateChallenge) GetHostAnswer() []byte {
	if m != nil {
		return m.HostAnswer
	}
	return nil
}

func (m *ProofOfReplicateChallenge) GetHostSignTime() *time.Time {
	if m != nil {
		return m.HostSignTime
	}
	return nil
}

func (m *ProofOfReplicateChallenge) GetHostSignature() []byte {
	if m != nil {
		return m.HostSignature
	}
	return nil
}

type FileChallengeQuestions struct {
	FileHash             []byte                     `protobuf:"bytes,1,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	ShardQuestions       []*ShardChallengeQuestions `protobuf:"bytes,2,rep,name=shard_questions,json=shardQuestions,proto3" json:"shard_questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *FileChallengeQuestions) Reset()         { *m = FileChallengeQuestions{} }
func (m *FileChallengeQuestions) String() string { return proto.CompactTextString(m) }
func (*FileChallengeQuestions) ProtoMessage()    {}
func (*FileChallengeQuestions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{7}
}
func (m *FileChallengeQuestions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChallengeQuestions.Unmarshal(m, b)
}
func (m *FileChallengeQuestions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChallengeQuestions.Marshal(b, m, deterministic)
}
func (m *FileChallengeQuestions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChallengeQuestions.Merge(m, src)
}
func (m *FileChallengeQuestions) XXX_Size() int {
	return xxx_messageInfo_FileChallengeQuestions.Size(m)
}
func (m *FileChallengeQuestions) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChallengeQuestions.DiscardUnknown(m)
}

var xxx_messageInfo_FileChallengeQuestions proto.InternalMessageInfo

func (m *FileChallengeQuestions) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *FileChallengeQuestions) GetShardQuestions() []*ShardChallengeQuestions {
	if m != nil {
		return m.ShardQuestions
	}
	return nil
}

type ShardChallengeQuestions struct {
	FileHash             []byte               `protobuf:"bytes,1,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	ShardHash            []byte               `protobuf:"bytes,2,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`
	PreparerAddress      []byte               `protobuf:"bytes,3,opt,name=preparer_address,json=preparerAddress,proto3" json:"preparer_address,omitempty"`
	QuestionCount        int32                `protobuf:"varint,4,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	Questions            []*ChallengeQuestion `protobuf:"bytes,5,rep,name=questions,proto3" json:"questions,omitempty"`
	PrepareTime          *time.Time           `protobuf:"bytes,6,opt,name=prepare_time,json=prepareTime,proto3,stdtime" json:"prepare_time,omitempty"`
	PreparerSignature    []byte               `protobuf:"bytes,7,opt,name=preparer_signature,json=preparerSignature,proto3" json:"preparer_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ShardChallengeQuestions) Reset()         { *m = ShardChallengeQuestions{} }
func (m *ShardChallengeQuestions) String() string { return proto.CompactTextString(m) }
func (*ShardChallengeQuestions) ProtoMessage()    {}
func (*ShardChallengeQuestions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{8}
}
func (m *ShardChallengeQuestions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardChallengeQuestions.Unmarshal(m, b)
}
func (m *ShardChallengeQuestions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardChallengeQuestions.Marshal(b, m, deterministic)
}
func (m *ShardChallengeQuestions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardChallengeQuestions.Merge(m, src)
}
func (m *ShardChallengeQuestions) XXX_Size() int {
	return xxx_messageInfo_ShardChallengeQuestions.Size(m)
}
func (m *ShardChallengeQuestions) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardChallengeQuestions.DiscardUnknown(m)
}

var xxx_messageInfo_ShardChallengeQuestions proto.InternalMessageInfo

func (m *ShardChallengeQuestions) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *ShardChallengeQuestions) GetShardHash() []byte {
	if m != nil {
		return m.ShardHash
	}
	return nil
}

func (m *ShardChallengeQuestions) GetPreparerAddress() []byte {
	if m != nil {
		return m.PreparerAddress
	}
	return nil
}

func (m *ShardChallengeQuestions) GetQuestionCount() int32 {
	if m != nil {
		return m.QuestionCount
	}
	return 0
}

func (m *ShardChallengeQuestions) GetQuestions() []*ChallengeQuestion {
	if m != nil {
		return m.Questions
	}
	return nil
}

func (m *ShardChallengeQuestions) GetPrepareTime() *time.Time {
	if m != nil {
		return m.PrepareTime
	}
	return nil
}

func (m *ShardChallengeQuestions) GetPreparerSignature() []byte {
	if m != nil {
		return m.PreparerSignature
	}
	return nil
}

type CheckFileStoreMetaRequest struct {
	FileHash             []byte     `protobuf:"bytes,1,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	RenterAddress        []byte     `protobuf:"bytes,2,opt,name=renter_address,json=renterAddress,proto3" json:"renter_address,omitempty"`
	RequesterAddress     []byte     `protobuf:"bytes,3,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
	RequestTime          *time.Time `protobuf:"bytes,4,opt,name=request_time,json=requestTime,proto3,stdtime" json:"request_time,omitempty"`
	Signature            []byte     `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CheckFileStoreMetaRequest) Reset()         { *m = CheckFileStoreMetaRequest{} }
func (m *CheckFileStoreMetaRequest) String() string { return proto.CompactTextString(m) }
func (*CheckFileStoreMetaRequest) ProtoMessage()    {}
func (*CheckFileStoreMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{9}
}
func (m *CheckFileStoreMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckFileStoreMetaRequest.Unmarshal(m, b)
}
func (m *CheckFileStoreMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckFileStoreMetaRequest.Marshal(b, m, deterministic)
}
func (m *CheckFileStoreMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckFileStoreMetaRequest.Merge(m, src)
}
func (m *CheckFileStoreMetaRequest) XXX_Size() int {
	return xxx_messageInfo_CheckFileStoreMetaRequest.Size(m)
}
func (m *CheckFileStoreMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckFileStoreMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckFileStoreMetaRequest proto.InternalMessageInfo

func (m *CheckFileStoreMetaRequest) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *CheckFileStoreMetaRequest) GetRenterAddress() []byte {
	if m != nil {
		return m.RenterAddress
	}
	return nil
}

func (m *CheckFileStoreMetaRequest) GetRequesterAddress() []byte {
	if m != nil {
		return m.RequesterAddress
	}
	return nil
}

func (m *CheckFileStoreMetaRequest) GetRequestTime() *time.Time {
	if m != nil {
		return m.RequestTime
	}
	return nil
}

func (m *CheckFileStoreMetaRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Result struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=guard.ResponseCode" json:"code,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ResponseTime         *time.Time   `protobuf:"bytes,3,opt,name=response_time,json=responseTime,proto3,stdtime" json:"response_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5b6eccdc9ebee8, []int{10}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_SUCCESS
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Result) GetResponseTime() *time.Time {
	if m != nil {
		return m.ResponseTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("guard.ResponseCode", ResponseCode_name, ResponseCode_value)
	proto.RegisterEnum("guard.ContractMeta_Schedule", ContractMeta_Schedule_name, ContractMeta_Schedule_value)
	proto.RegisterEnum("guard.Contract_ContractState", Contract_ContractState_name, Contract_ContractState_value)
	proto.RegisterEnum("guard.FileStoreStatus_MetaState", FileStoreStatus_MetaState_name, FileStoreStatus_MetaState_value)
	proto.RegisterType((*Log)(nil), "guard.Log")
	proto.RegisterType((*ContractMeta)(nil), "guard.ContractMeta")
	proto.RegisterType((*Contract)(nil), "guard.Contract")
	proto.RegisterType((*FileStoreMeta)(nil), "guard.FileStoreMeta")
	proto.RegisterType((*FileStoreStatus)(nil), "guard.FileStoreStatus")
	proto.RegisterType((*ChallengeQuestion)(nil), "guard.ChallengeQuestion")
	proto.RegisterType((*ProofOfReplicateChallenge)(nil), "guard.ProofOfReplicateChallenge")
	proto.RegisterType((*FileChallengeQuestions)(nil), "guard.FileChallengeQuestions")
	proto.RegisterType((*ShardChallengeQuestions)(nil), "guard.ShardChallengeQuestions")
	proto.RegisterType((*CheckFileStoreMetaRequest)(nil), "guard.CheckFileStoreMetaRequest")
	proto.RegisterType((*Result)(nil), "guard.Result")
}

func init() { proto.RegisterFile("protos/guard/guard.proto", fileDescriptor_ad5b6eccdc9ebee8) }

var fileDescriptor_ad5b6eccdc9ebee8 = []byte{
	// 1702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xdd, 0x8e, 0xdb, 0xc6,
	0x15, 0x36, 0x25, 0x71, 0x57, 0x3a, 0x22, 0x25, 0x7a, 0xe2, 0xba, 0xb2, 0x1a, 0xd7, 0x8a, 0x0a,
	0xd7, 0xeb, 0x16, 0x96, 0x81, 0x4d, 0x90, 0x9b, 0xa4, 0x28, 0x14, 0x49, 0xbb, 0xde, 0x42, 0x2b,
	0x6d, 0x86, 0x5a, 0xa0, 0xee, 0x0d, 0x41, 0x93, 0x23, 0x89, 0x88, 0xc4, 0x51, 0xf8, 0xe3, 0xc4,
	0xb9, 0xe8, 0x6d, 0x6f, 0x8b, 0xa2, 0x0f, 0x50, 0xf4, 0x25, 0x7a, 0x57, 0xa0, 0xcf, 0xd0, 0x07,
	0xe8, 0x23, 0xf4, 0xb6, 0x97, 0xc5, 0x9c, 0x19, 0x52, 0xbf, 0xeb, 0xca, 0xe8, 0x8d, 0xbd, 0xf3,
	0x9d, 0xef, 0x70, 0xce, 0x9c, 0x9f, 0x6f, 0x66, 0x17, 0x1a, 0xab, 0x88, 0x27, 0x3c, 0x7e, 0x39,
	0x4b, 0xdd, 0xc8, 0x97, 0xff, 0x76, 0x10, 0x22, 0x3a, 0x2e, 0x9a, 0x2f, 0x66, 0x41, 0x32, 0x4f,
	0xdf, 0x74, 0x3c, 0xbe, 0x7c, 0x39, 0xe3, 0x33, 0xfe, 0x12, 0xad, 0x6f, 0xd2, 0x29, 0xae, 0x70,
	0x81, 0x3f, 0x49, 0xaf, 0xe6, 0x93, 0x19, 0xe7, 0xb3, 0x05, 0x5b, 0xb3, 0x92, 0x60, 0xc9, 0xe2,
	0xc4, 0x5d, 0xae, 0x14, 0xa1, 0xa9, 0x36, 0x8c, 0xe7, 0x6e, 0xc4, 0x7c, 0xf5, 0x9f, 0xb4, 0xb5,
	0xff, 0xa0, 0x41, 0x71, 0xc8, 0x67, 0xe4, 0x0b, 0xa8, 0x7a, 0x73, 0x37, 0x9c, 0x31, 0x47, 0x78,
	0x37, 0xb4, 0x96, 0x76, 0x56, 0x3d, 0x6f, 0x76, 0xe4, 0xa7, 0x3b, 0xd9, 0xa7, 0x3b, 0x93, 0xec,
	0xd3, 0x14, 0x24, 0x5d, 0x00, 0xe4, 0x97, 0x70, 0x5f, 0x39, 0xf3, 0x28, 0x98, 0x05, 0xa1, 0x9b,
	0xf0, 0xa8, 0x51, 0x68, 0x69, 0x67, 0x06, 0xb5, 0xa4, 0x61, 0x9c, 0xe3, 0xe4, 0x21, 0x9c, 0x48,
	0xac, 0x51, 0x44, 0x86, 0x5a, 0xb5, 0xff, 0xa1, 0x83, 0xd1, 0xe3, 0x61, 0x12, 0xb9, 0x5e, 0x72,
	0xcd, 0x12, 0x97, 0x3c, 0x81, 0xaa, 0xa7, 0xd6, 0x4e, 0xe0, 0x63, 0x48, 0x06, 0x85, 0x0c, 0xba,
	0xf2, 0xc9, 0x53, 0xa8, 0x45, 0x2c, 0x4c, 0x58, 0xe4, 0xb8, 0xbe, 0x1f, 0xb1, 0x38, 0x56, 0x7b,
	0x9a, 0x12, 0xed, 0x4a, 0x90, 0x7c, 0x02, 0xc6, 0x9c, 0xc7, 0x49, 0x4e, 0x92, 0xdb, 0x56, 0x05,
	0x96, 0x51, 0x1e, 0x03, 0x88, 0xac, 0xf8, 0xce, 0xdc, 0x8d, 0xe7, 0x8d, 0x12, 0x12, 0x2a, 0x88,
	0xbc, 0x72, 0xe3, 0xb9, 0x88, 0x44, 0x9a, 0x83, 0xd0, 0x67, 0xdf, 0x37, 0xf4, 0x96, 0x76, 0xa6,
	0x53, 0xe9, 0x71, 0x25, 0x10, 0xf2, 0x73, 0xa8, 0x4b, 0xc2, 0x34, 0x58, 0x30, 0x27, 0x0e, 0x7e,
	0x60, 0x8d, 0x93, 0x96, 0x76, 0x56, 0xa4, 0x26, 0xc2, 0x17, 0xc1, 0x82, 0xd9, 0xc1, 0x0f, 0x8c,
	0xfc, 0x04, 0x2a, 0xc8, 0xc0, 0x6d, 0x4e, 0x71, 0x9b, 0xb2, 0x00, 0x70, 0x97, 0x5f, 0x03, 0x88,
	0xc0, 0x9d, 0x38, 0x71, 0xa3, 0xa4, 0x51, 0xfe, 0x5f, 0x15, 0xf8, 0xaa, 0xf4, 0xc7, 0x7f, 0x3d,
	0xd1, 0x68, 0x45, 0xf8, 0xd8, 0xc2, 0x85, 0x7c, 0x01, 0x65, 0xfc, 0x00, 0x0b, 0xfd, 0x46, 0xe5,
	0x48, 0xf7, 0x53, 0xe1, 0x31, 0x08, 0x7d, 0xf2, 0x33, 0x30, 0xb1, 0xfb, 0xf2, 0x34, 0x01, 0x86,
	0x67, 0x20, 0x98, 0xe5, 0xe9, 0x29, 0xd4, 0x58, 0xec, 0x45, 0xfc, 0xbb, 0x9c, 0x55, 0x95, 0x19,
	0x97, 0x68, 0x46, 0x7b, 0x00, 0xfa, 0x2a, 0x0a, 0x3c, 0xd6, 0x30, 0x30, 0x09, 0x72, 0x21, 0x0a,
	0xef, 0x2e, 0x79, 0x1a, 0x26, 0x0d, 0x13, 0x61, 0xb5, 0xc2, 0xee, 0xe1, 0x8b, 0x85, 0x9b, 0xb0,
	0xc8, 0x5d, 0x38, 0x8a, 0x52, 0x43, 0x8a, 0xb5, 0x36, 0x74, 0x25, 0x79, 0x00, 0xf5, 0x95, 0xfb,
	0x8e, 0xa7, 0x89, 0x13, 0x7b, 0x73, 0xe6, 0xa7, 0x0b, 0xd6, 0xa8, 0xb7, 0xb4, 0xb3, 0xda, 0xf9,
	0xc7, 0x1d, 0x39, 0x49, 0x9b, 0x2d, 0xd4, 0xb1, 0x15, 0x87, 0xd6, 0xa4, 0x53, 0xb6, 0x16, 0x15,
	0x0d, 0xd3, 0xa5, 0x23, 0xd1, 0xb8, 0x61, 0xc9, 0x8a, 0x86, 0xe9, 0xf2, 0x46, 0x22, 0xed, 0xcf,
	0xa0, 0x9c, 0x93, 0xab, 0x70, 0x7a, 0x3d, 0x1e, 0x4d, 0x5e, 0x0d, 0x5f, 0x5b, 0xf7, 0x88, 0x09,
	0x95, 0xaf, 0x6f, 0xbb, 0x74, 0x32, 0xa0, 0xc3, 0xd7, 0x96, 0x46, 0x0c, 0x28, 0x77, 0x47, 0xa3,
	0xdb, 0xee, 0x70, 0xf8, 0xda, 0x2a, 0xb4, 0xff, 0x56, 0x82, 0x72, 0x16, 0x00, 0x79, 0x09, 0xe5,
	0xac, 0x59, 0xd5, 0x3c, 0x7d, 0x74, 0x20, 0x46, 0x9a, 0x93, 0xc8, 0xa7, 0xa0, 0xc7, 0x89, 0x9b,
	0x30, 0x6c, 0xe3, 0xda, 0xf9, 0xe3, 0x1d, 0x76, 0xfe, 0x83, 0x2d, 0x48, 0x54, 0x72, 0xc9, 0x73,
	0xb0, 0xd4, 0x10, 0xc4, 0xc1, 0x2c, 0x74, 0x93, 0x34, 0xca, 0x06, 0xab, 0x2e, 0x71, 0x3b, 0x83,
	0x45, 0xf5, 0x70, 0x10, 0xd6, 0x44, 0xd9, 0xe9, 0xa6, 0x40, 0xd7, 0xb4, 0x11, 0x10, 0x55, 0x64,
	0x41, 0x64, 0xbe, 0x54, 0x04, 0xfd, 0xc8, 0x86, 0xb2, 0xa4, 0xaf, 0x8d, 0xae, 0xa8, 0x0e, 0xcf,
	0xc1, 0xda, 0xf8, 0x9e, 0xdc, 0xf8, 0x44, 0x46, 0xb8, 0xe6, 0xca, 0xad, 0x9f, 0x83, 0x92, 0x15,
	0x67, 0xc1, 0x67, 0x8d, 0xd3, 0x56, 0xf1, 0xac, 0x7a, 0x0e, 0x2a, 0x0d, 0x43, 0x3e, 0xa3, 0x15,
	0x69, 0x15, 0x82, 0xf5, 0x1b, 0xb0, 0x16, 0x6e, 0x9c, 0x38, 0x4b, 0xee, 0x07, 0xd3, 0x77, 0x32,
	0xc6, 0x63, 0x67, 0xa6, 0x26, 0x3c, 0xaf, 0xd1, 0x11, 0x23, 0x7c, 0x06, 0x75, 0xd9, 0xfb, 0xeb,
	0x00, 0x2b, 0x18, 0x60, 0x0d, 0xe1, 0x3c, 0xbe, 0xf6, 0x6f, 0xc1, 0xdc, 0x2a, 0x02, 0xa9, 0x80,
	0xde, 0xa7, 0xdd, 0x8b, 0x89, 0x75, 0x8f, 0x00, 0x9c, 0xd8, 0x57, 0x97, 0xa3, 0x41, 0x5f, 0x76,
	0xc5, 0xed, 0xcd, 0x70, 0xdc, 0xed, 0x0f, 0xfa, 0x56, 0x81, 0x94, 0xa1, 0x34, 0x1c, 0xdb, 0x13,
	0xab, 0x28, 0xf0, 0x5e, 0x77, 0xd4, 0x1b, 0x0c, 0x07, 0x7d, 0xab, 0x24, 0x3c, 0x7a, 0xc3, 0xb1,
	0x3d, 0xe8, 0x5b, 0x7a, 0xfb, 0xcf, 0x25, 0x30, 0x51, 0x26, 0x12, 0x1e, 0x31, 0x94, 0xbf, 0x7d,
	0x75, 0xd3, 0x0e, 0xa9, 0xdb, 0x96, 0xa4, 0x14, 0x76, 0x24, 0x25, 0x33, 0xa2, 0x22, 0x15, 0x71,
	0xa4, 0xd0, 0x88, 0x62, 0xb4, 0xad, 0x37, 0xa5, 0xff, 0x4f, 0x6f, 0xf4, 0x0f, 0xd5, 0x9b, 0x67,
	0x50, 0xf7, 0xe6, 0xcc, 0xfb, 0xc6, 0x99, 0x46, 0xec, 0xdb, 0x94, 0x85, 0xde, 0x3b, 0x6c, 0x0a,
	0x9d, 0xd6, 0x10, 0xbe, 0xc8, 0x50, 0x71, 0x06, 0x59, 0x9c, 0x29, 0x63, 0xa8, 0x99, 0x45, 0x5a,
	0x46, 0xe0, 0x82, 0x31, 0x21, 0xdc, 0xaa, 0xb7, 0x84, 0xb5, 0x8c, 0xd6, 0x8a, 0x44, 0x84, 0x39,
	0x17, 0x6e, 0x0f, 0x45, 0xa5, 0xb2, 0x21, 0xdc, 0x3d, 0x94, 0x93, 0xa7, 0x50, 0x5b, 0x06, 0x61,
	0xb0, 0x4c, 0x97, 0x0e, 0xa2, 0x52, 0xf6, 0x74, 0x6a, 0x2a, 0xd4, 0x46, 0x50, 0x48, 0x54, 0xc4,
	0x3c, 0xfe, 0x96, 0x45, 0x4e, 0x32, 0x8f, 0x58, 0x3c, 0xe7, 0x0b, 0x1f, 0xa5, 0x4f, 0xa7, 0x96,
	0x32, 0x4c, 0x32, 0xfc, 0x80, 0x48, 0x1a, 0x87, 0x44, 0x72, 0x4f, 0x70, 0xcd, 0x7d, 0xc1, 0x6d,
	0xff, 0xb5, 0x04, 0xf5, 0xbc, 0x2d, 0x44, 0xcb, 0xa5, 0x31, 0xf9, 0x12, 0xea, 0xb2, 0xa8, 0x02,
	0x73, 0x96, 0x2c, 0x71, 0x95, 0xbc, 0x3c, 0x50, 0x93, 0xb2, 0xd5, 0x47, 0xd4, 0x9c, 0x6e, 0xb5,
	0xd5, 0xe7, 0xdb, 0x22, 0xd3, 0xda, 0xf5, 0x91, 0x9b, 0x74, 0x04, 0x77, 0x4b, 0x67, 0x5e, 0x40,
	0x25, 0x13, 0x2a, 0x71, 0x85, 0x8a, 0xc9, 0xac, 0xef, 0x08, 0x14, 0x5d, 0x33, 0x0e, 0xca, 0x52,
	0xe9, 0xb0, 0x2c, 0x8d, 0x80, 0xc8, 0x44, 0x44, 0xcc, 0x63, 0xc1, 0x5b, 0xf6, 0x81, 0x7a, 0x83,
	0xbe, 0x54, 0xba, 0x2a, 0xbd, 0xd9, 0x14, 0x91, 0x93, 0xf7, 0x89, 0x48, 0x17, 0xaa, 0x5e, 0x8a,
	0x3d, 0x8c, 0x7b, 0x9e, 0x1e, 0xb9, 0x27, 0x48, 0xa7, 0xbb, 0xb4, 0xa3, 0x7c, 0x87, 0x76, 0x54,
	0xf2, 0xa4, 0x6e, 0xea, 0x86, 0x09, 0x15, 0xa9, 0x15, 0x57, 0xa3, 0x4b, 0x4b, 0x13, 0x97, 0x0d,
	0xbd, 0x1d, 0x8d, 0xc4, 0xa2, 0x40, 0x2c, 0x30, 0x6e, 0xba, 0x74, 0x72, 0xd5, 0x1d, 0x3a, 0x4a,
	0x41, 0x32, 0x2d, 0x29, 0x89, 0x9f, 0xfa, 0xe3, 0xd1, 0xc0, 0xd2, 0xdb, 0x7f, 0xd7, 0xe0, 0x7e,
	0x6f, 0xee, 0x2e, 0x16, 0x2c, 0x9c, 0xb1, 0xaf, 0x53, 0x16, 0x27, 0x01, 0x0f, 0x77, 0xde, 0x34,
	0xda, 0xee, 0x9b, 0x66, 0xf7, 0x55, 0x54, 0xd8, 0x7f, 0x15, 0x89, 0x07, 0xd8, 0x3c, 0x0d, 0xbf,
	0x51, 0xcf, 0x9e, 0xa2, 0x9c, 0x1e, 0x84, 0xe4, 0xb3, 0xe7, 0x13, 0x30, 0x22, 0x37, 0xf4, 0xf9,
	0xd2, 0x09, 0x79, 0xe8, 0xc9, 0x02, 0xeb, 0xb4, 0x2a, 0xb1, 0x91, 0x80, 0x44, 0x97, 0xb3, 0xef,
	0x57, 0xcc, 0x4b, 0x1c, 0x37, 0x8c, 0xbf, 0x63, 0x11, 0xd6, 0xd5, 0xa0, 0x86, 0x04, 0xbb, 0x88,
	0xb5, 0xff, 0x53, 0x80, 0x47, 0x37, 0x11, 0xe7, 0xd3, 0xf1, 0x94, 0xb2, 0xd5, 0x22, 0xf0, 0xdc,
	0x84, 0xe5, 0x07, 0x22, 0x9f, 0x41, 0xf9, 0x5b, 0x75, 0x28, 0xd5, 0xe8, 0x8d, 0xac, 0xf1, 0x76,
	0x0f, 0x4d, 0x73, 0x26, 0xb9, 0x84, 0x9a, 0x97, 0x99, 0x65, 0x75, 0x0b, 0x47, 0x56, 0xd7, 0xcc,
	0xfd, 0xb0, 0xc0, 0x7b, 0x73, 0x5a, 0x3c, 0xf0, 0x30, 0x3a, 0xd0, 0x05, 0xa5, 0x43, 0x5d, 0x20,
	0x72, 0x2a, 0xd3, 0xbe, 0x99, 0x0d, 0xc0, 0xac, 0x23, 0x42, 0x2e, 0x36, 0x2e, 0x69, 0x19, 0xf7,
	0xc9, 0x91, 0x71, 0x1b, 0xd9, 0x35, 0x8e, 0x61, 0xef, 0x5f, 0xf6, 0xa7, 0x07, 0x2e, 0xfb, 0xf6,
	0xef, 0xe1, 0xa1, 0x18, 0xfd, 0xbd, 0x4c, 0xee, 0x5c, 0x2c, 0xda, 0xce, 0xc5, 0x72, 0x99, 0x3d,
	0x78, 0xb3, 0x7c, 0x8b, 0x06, 0x12, 0x83, 0xf6, 0x53, 0x55, 0x1a, 0x14, 0xce, 0xfd, 0xaf, 0xd2,
	0x1a, 0xba, 0xe5, 0xeb, 0xf6, 0x3f, 0x0b, 0xf0, 0xe3, 0x3b, 0xb8, 0xef, 0x8f, 0x60, 0xbb, 0xbd,
	0x0b, 0xbb, 0xed, 0xfd, 0x1c, 0xac, 0x55, 0xc4, 0x56, 0x6e, 0xb4, 0x71, 0x7f, 0xaa, 0x67, 0x51,
	0x86, 0x6f, 0x3c, 0x6a, 0xb3, 0x53, 0xa8, 0x7b, 0x42, 0xf6, 0xb1, 0x99, 0xa1, 0xf2, 0xaa, 0xf8,
	0x1c, 0x2a, 0xeb, 0xc3, 0xea, 0x78, 0xd8, 0xbb, 0xfb, 0x70, 0x4d, 0x25, 0x3d, 0x30, 0xd4, 0x8e,
	0x1f, 0x56, 0xce, 0xaa, 0xf2, 0xc2, 0x6a, 0xbe, 0x00, 0x92, 0x1f, 0x67, 0xb7, 0xa2, 0xf7, 0x33,
	0xcb, 0xba, 0xaa, 0xff, 0xd6, 0xe0, 0x51, 0x0f, 0xaf, 0xd1, 0xad, 0xab, 0x80, 0x61, 0x54, 0xef,
	0xcf, 0xeb, 0x91, 0xbf, 0x54, 0xe1, 0x8d, 0x88, 0x9f, 0xdb, 0x4b, 0xb0, 0x95, 0x1b, 0x32, 0x72,
	0x0f, 0x0c, 0x85, 0xc9, 0x14, 0x1c, 0xfb, 0xd6, 0xa8, 0x2a, 0x2f, 0x4c, 0xc1, 0xc7, 0x50, 0x59,
	0x9f, 0x5c, 0x57, 0xf5, 0xce, 0x4f, 0xfc, 0x27, 0x0d, 0x4e, 0x28, 0x8b, 0xd3, 0x45, 0x42, 0x9e,
	0x41, 0xc9, 0xe3, 0xbe, 0xfc, 0x1d, 0xb6, 0x96, 0xbf, 0xb9, 0x29, 0x8b, 0x57, 0x3c, 0x8c, 0x59,
	0x8f, 0xfb, 0x8c, 0x22, 0x81, 0x34, 0xe0, 0x74, 0xc9, 0xe2, 0xd8, 0x9d, 0x49, 0x6d, 0xa8, 0xd0,
	0x6c, 0x49, 0x06, 0x60, 0x46, 0x8a, 0x2f, 0x23, 0x2e, 0x1e, 0x3b, 0x83, 0x99, 0x9b, 0x30, 0xfc,
	0xc2, 0x03, 0x63, 0x73, 0x5b, 0xa1, 0xed, 0xf6, 0x6d, 0xaf, 0x37, 0xb0, 0x6d, 0xeb, 0x1e, 0x69,
	0xc2, 0x43, 0xf1, 0x5e, 0xec, 0x4e, 0x6e, 0xe9, 0xc0, 0xb9, 0x18, 0xd3, 0xeb, 0xee, 0xc4, 0x19,
	0x50, 0x3a, 0xa6, 0x96, 0x46, 0x1e, 0xc1, 0x8f, 0x7a, 0xe3, 0xeb, 0x9b, 0xdb, 0xc9, 0xc0, 0xe9,
	0xf6, 0xfb, 0x74, 0x60, 0xdb, 0xca, 0x54, 0x20, 0x75, 0xa8, 0x8e, 0x27, 0xaf, 0x06, 0x54, 0x01,
	0x0f, 0xce, 0xff, 0x52, 0x00, 0xe3, 0x12, 0x45, 0x86, 0x45, 0x6f, 0xc5, 0xef, 0x59, 0x5f, 0xc2,
	0x47, 0x76, 0xfa, 0x66, 0x19, 0x24, 0xdb, 0xef, 0xc9, 0x87, 0x87, 0x6f, 0xfa, 0xa6, 0xb9, 0x4e,
	0x90, 0xc8, 0x5e, 0x0f, 0x40, 0x1a, 0xae, 0xc2, 0x29, 0x27, 0xcd, 0x8e, 0xfa, 0x6b, 0x01, 0x4d,
	0x43, 0x91, 0x08, 0x01, 0xaa, 0x36, 0x6a, 0x3e, 0x3a, 0x68, 0x5b, 0xf1, 0x28, 0x21, 0xbf, 0x02,
	0xd3, 0x66, 0xe1, 0x7a, 0xcc, 0xc9, 0xe3, 0x8d, 0xcd, 0xf7, 0x27, 0x7d, 0x37, 0x86, 0x11, 0x90,
	0xfd, 0xee, 0x25, 0xad, 0x7c, 0xda, 0xee, 0x68, 0xec, 0xe6, 0x1d, 0x47, 0xfc, 0xea, 0xf4, 0x77,
	0xf2, 0x2f, 0x2b, 0x6f, 0x4e, 0xb0, 0x70, 0x9f, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x8b,
	0xff, 0x33, 0x83, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GuardServiceClient is the client API for GuardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuardServiceClient interface {
	SubmitFileStoreMeta(ctx context.Context, in *FileStoreStatus, opts ...grpc.CallOption) (*Result, error)
	StatusInfo(ctx context.Context, in *shared.RuntimeInfoRequest, opts ...grpc.CallOption) (*shared.RuntimeInfoReport, error)
	SendQuestions(ctx context.Context, in *FileChallengeQuestions, opts ...grpc.CallOption) (*Result, error)
	CheckFileStoreMeta(ctx context.Context, in *CheckFileStoreMetaRequest, opts ...grpc.CallOption) (*FileStoreStatus, error)
}

type guardServiceClient struct {
	cc *grpc.ClientConn
}

func NewGuardServiceClient(cc *grpc.ClientConn) GuardServiceClient {
	return &guardServiceClient{cc}
}

func (c *guardServiceClient) SubmitFileStoreMeta(ctx context.Context, in *FileStoreStatus, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/guard.GuardService/SubmitFileStoreMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardServiceClient) StatusInfo(ctx context.Context, in *shared.RuntimeInfoRequest, opts ...grpc.CallOption) (*shared.RuntimeInfoReport, error) {
	out := new(shared.RuntimeInfoReport)
	err := c.cc.Invoke(ctx, "/guard.GuardService/StatusInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardServiceClient) SendQuestions(ctx context.Context, in *FileChallengeQuestions, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/guard.GuardService/SendQuestions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardServiceClient) CheckFileStoreMeta(ctx context.Context, in *CheckFileStoreMetaRequest, opts ...grpc.CallOption) (*FileStoreStatus, error) {
	out := new(FileStoreStatus)
	err := c.cc.Invoke(ctx, "/guard.GuardService/CheckFileStoreMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuardServiceServer is the server API for GuardService service.
type GuardServiceServer interface {
	SubmitFileStoreMeta(context.Context, *FileStoreStatus) (*Result, error)
	StatusInfo(context.Context, *shared.RuntimeInfoRequest) (*shared.RuntimeInfoReport, error)
	SendQuestions(context.Context, *FileChallengeQuestions) (*Result, error)
	CheckFileStoreMeta(context.Context, *CheckFileStoreMetaRequest) (*FileStoreStatus, error)
}

// UnimplementedGuardServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGuardServiceServer struct {
}

func (*UnimplementedGuardServiceServer) SubmitFileStoreMeta(ctx context.Context, req *FileStoreStatus) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitFileStoreMeta not implemented")
}
func (*UnimplementedGuardServiceServer) StatusInfo(ctx context.Context, req *shared.RuntimeInfoRequest) (*shared.RuntimeInfoReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusInfo not implemented")
}
func (*UnimplementedGuardServiceServer) SendQuestions(ctx context.Context, req *FileChallengeQuestions) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendQuestions not implemented")
}
func (*UnimplementedGuardServiceServer) CheckFileStoreMeta(ctx context.Context, req *CheckFileStoreMetaRequest) (*FileStoreStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFileStoreMeta not implemented")
}

func RegisterGuardServiceServer(s *grpc.Server, srv GuardServiceServer) {
	s.RegisterService(&_GuardService_serviceDesc, srv)
}

func _GuardService_SubmitFileStoreMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileStoreStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServiceServer).SubmitFileStoreMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guard.GuardService/SubmitFileStoreMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServiceServer).SubmitFileStoreMeta(ctx, req.(*FileStoreStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardService_StatusInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shared.RuntimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServiceServer).StatusInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guard.GuardService/StatusInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServiceServer).StatusInfo(ctx, req.(*shared.RuntimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardService_SendQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileChallengeQuestions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServiceServer).SendQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guard.GuardService/SendQuestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServiceServer).SendQuestions(ctx, req.(*FileChallengeQuestions))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardService_CheckFileStoreMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFileStoreMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServiceServer).CheckFileStoreMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guard.GuardService/CheckFileStoreMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServiceServer).CheckFileStoreMeta(ctx, req.(*CheckFileStoreMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guard.GuardService",
	HandlerType: (*GuardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitFileStoreMeta",
			Handler:    _GuardService_SubmitFileStoreMeta_Handler,
		},
		{
			MethodName: "StatusInfo",
			Handler:    _GuardService_StatusInfo_Handler,
		},
		{
			MethodName: "SendQuestions",
			Handler:    _GuardService_SendQuestions_Handler,
		},
		{
			MethodName: "CheckFileStoreMeta",
			Handler:    _GuardService_CheckFileStoreMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/guard/guard.proto",
}
